# model [psp/e4e]
model_id: psp
stylegan_path: packages/stylegan2_rosinality/ckpt/kface_50000.pt
# stylegan_path: packages/stylegan2_rosinality/ckpt/stylegan2-ffhq-config-f.pt

# multi-GPUs
use_mGPU: True

# validation
use_validation: True
valid_dataset_root: ./assets/k-celeb

# wandb
use_wandb: False
wandb_alert_thres: 1000

# root
train_dataset_root_list: [
                # '../dataset/CelebHQ',
                # '../dataset/ffhq70k'
                "../dataset/kface_wild_1024"
            ]

save_root: train_result


# optimizer 
optimizer: Ranger # [Ranger, Adam]
betas: [0.95, 0.999] # default: Adam (0.9, 0.999) / Ranger (0.95, 0.999)

# weight of loss
# for psp
# learning rate
lr_E: 0.0001
W_adv: 0
W_id: 0.1
W_recon: 1
W_cycle: 0
W_lpips: 2
W_attr: 0
W_feat: 0

# for e4e
# use_progressive_steps: True
# progressive_start: 20000
# progressive_step_cycle: 2000

# lr_G: 0.0001
# lr_D: 0.00002
# W_adv: 0.1
# W_id: 0.1
# W_recon: 1
# W_cycle: 0
# W_lpips: 0.8
# W_attr: 0
# W_feat: 0
# W_reg: 0.0002

# hyperparameters
batch_per_gpu: 8
max_step: 400000

# log cycle
loss_cycle: 10
test_cycle: 500
ckpt_cycle: 5000

# ckpt path
# load checkpoints from ./train_result/{ckpt_id}/ckpt/G_{ckpt_step}.pt
# if ckpt_id is empty, load G_latest.pt and D_latest.pt
# Note that an empty space is None, but None is "None"
load_ckpt: False
ckpt_id:
ckpt_step:
